# 1. 安全協定：SASL + SSL
security.protocol=SASL_SSL
sasl.mechanism=PLAIN

# 2. 帳號密碼 (這裡是 admin)
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="SECRET_PASSWORD";

# 3. SSL 信任設定 (Client 只需要 Truststore)
# 注意：這裡的路徑是指「容器內的路徑」，等一下我們會掛載進去
ssl.truststore.location=/etc/kafka/secrets/kafka.server.truststore.jks
ssl.truststore.password=YOUR_PASSWORD

# 4. 如果是用 IP 連線，為了避免 SSL 檢查主機名稱報錯，先關掉驗證
ssl.endpoint.identification.algorithm=
