security.protocol=SASL_SSL
sasl.mechanism=PLAIN
# 注意：這裡改成 Alice 的帳號密碼
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="alice" password="SECRET_PASSWORD";

# SSL 設定跟 admin 一樣，因為大家連的是同一家銀行
ssl.truststore.location=/etc/kafka/secrets/kafka.server.truststore.jks
ssl.truststore.password=YOUR_PASSWORD
ssl.endpoint.identification.algorithm=
