KafkaServer {
   org.apache.kafka.common.security.plain.PlainLoginModule required
   username="admin"
   password="SECRET_PASSWORD"
   user_admin="SECRET_PASSWORD"
   user_alice="SECRET_PASSWORD";
};
